/*
 * generated by Xtext 2.36.0
 */
package xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class EduquizzUiModule extends AbstractEduquizzUiModule {

	public EduquizzUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
