/*
 * generated by Xtext 2.36.0
 */
package xtext.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractEduquizzScopeProvider extends DelegatingScopeProvider {
}
