/*
 * generated by Xtext 2.36.0
 */
package xtext.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import xtext.parser.antlr.internal.InternalEduquizzParser;
import xtext.services.EduquizzGrammarAccess;

public class EduquizzParser extends AbstractAntlrParser {

	@Inject
	private EduquizzGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalEduquizzParser createParser(XtextTokenStream stream) {
		return new InternalEduquizzParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Questionnaire";
	}

	public EduquizzGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(EduquizzGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
