/**
 * generated by Xtext 2.36.0
 */
package xtext.formatting2;

import com.google.inject.Inject;
import java.util.Arrays;
import mm1.Question;
import mm1.Questionnaire;
import mm1.Reponse;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.formatting2.AbstractFormatter2;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import org.eclipse.xtext.resource.XtextResource;
import org.eclipse.xtext.xbase.lib.Extension;
import org.eclipse.xtext.xbase.lib.XbaseGenerated;
import xtext.services.EduquizzGrammarAccess;

@SuppressWarnings("all")
public class EduquizzFormatter extends AbstractFormatter2 {
  @Inject
  @Extension
  private EduquizzGrammarAccess _eduquizzGrammarAccess;

  protected void _format(final Questionnaire questionnaire, @Extension final IFormattableDocument document) {
    EList<Question> _question = questionnaire.getQuestion();
    for (final Question question : _question) {
      document.<Question>format(question);
    }
  }

  protected void _format(final Question question, @Extension final IFormattableDocument document) {
    EList<Reponse> _reponse = question.getReponse();
    for (final Reponse reponse : _reponse) {
      document.<Reponse>format(reponse);
    }
  }

  @XbaseGenerated
  public void format(final Object questionnaire, final IFormattableDocument document) {
    if (questionnaire instanceof XtextResource) {
      _format((XtextResource)questionnaire, document);
      return;
    } else if (questionnaire instanceof Questionnaire) {
      _format((Questionnaire)questionnaire, document);
      return;
    } else if (questionnaire instanceof Question) {
      _format((Question)questionnaire, document);
      return;
    } else if (questionnaire instanceof EObject) {
      _format((EObject)questionnaire, document);
      return;
    } else if (questionnaire == null) {
      _format((Void)null, document);
      return;
    } else if (questionnaire != null) {
      _format(questionnaire, document);
      return;
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(questionnaire, document).toString());
    }
  }
}
