/*
 * generated by Xtext 2.36.0
 */
package xtext.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import xtext.EduquizzRuntimeModule;
import xtext.EduquizzStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class EduquizzIdeSetup extends EduquizzStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new EduquizzRuntimeModule(), new EduquizzIdeModule()));
	}
	
}
