/*
 * generated by Xtext 2.36.0
 */
package xtext;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class EduquizzStandaloneSetup extends EduquizzStandaloneSetupGenerated {

	public static void doSetup() {
		new EduquizzStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
